name: Mypy Type Checking

on:
  push:
    # Run on all branches
    paths:
      - 'src/**/*.py'

  pull_request:
    # Run on all PRs, regardless of base or head branch
    paths:
      - 'src/**/*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Mypy
        run: mypy src/

